(() => {
  const DEFAULT_STATE={version:2,patches:{},sectionOrder:[],site:{title:'',description:'',customCss:'',theme:{}},videos:{}};
  const DEFAULT_THEME={primary:'#fa4a98',background:'#0a0508',foreground:'#fff7fb',card:'#171015',muted:'#b7aab1'};
  let state=JSON.parse(JSON.stringify(DEFAULT_STATE)),dirty=false,currentView='content',previousView='content',selectedId='';
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],preview=$('#preview');
  function ensureState(data={}){state={...DEFAULT_STATE,...data,patches:{...(data.patches||{})},videos:{...(data.videos||{})},site:{...DEFAULT_STATE.site,...(data.site||{}),theme:{...(data.site?.theme||{})}}}}
  function toast(m){const t=$('#toast');t.textContent=m;t.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.add('hidden'),2800)}
  function setDirty(v=true){dirty=v;const b=$('#saveStatus');b.classList.toggle('dirty',v);b.classList.toggle('saved',!v);b.querySelector('span:last-child').textContent=v?'Alterações não salvas':'Salvo';syncRaw()}
  async function api(url,o={}){const h={...(o.headers||{})};if(o.body&&!(o.body instanceof FormData))h['content-type']='application/json';const r=await fetch(url,{...o,headers:h});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`Erro ${r.status}`);return d}
  async function checkSession(){try{const s=await api('/api/session');if(s.authenticated)await showApp()}catch{}}
  async function showApp(){$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');try{ensureState(await api('/api/content'))}catch{ensureState({})}syncSiteFields();preview.src='/?admin-preview=1&t='+Date.now()}
  async function save(){try{$('#saveBtn').disabled=true;state.version=2;await api('/api/content',{method:'PUT',body:JSON.stringify(state)});setDirty(false);toast('Tudo salvo com sucesso.')}catch(e){toast(e.message)}finally{$('#saveBtn').disabled=false}}
  function doc(){return preview.contentDocument}
  function openView(n){if(n==='selected'&&currentView!=='selected')previousView=currentView;currentView=n;$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===n));$$('[data-view-panel]').forEach(p=>p.classList.toggle('active',p.dataset.viewPanel===n))}
  $$('.nav-item,[data-view]').forEach(b=>b.addEventListener('click',e=>{const n=e.currentTarget.dataset.view;if(n)openView(n)}));
  $('#backFromSelected').onclick=()=>openView(previousView||'content');$('#saveBtn').onclick=save;$('#reloadBtn').onclick=()=>preview.src='/?admin-preview=1&t='+Date.now();$('#logoutBtn').onclick=async()=>{await api('/api/logout',{method:'POST'}).catch(()=>{});location.reload()};
  $('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';try{await api('/api/login',{method:'POST',body:JSON.stringify({password:$('#password').value})});await showApp()}catch(err){$('#loginError').textContent=err.message}});
  $$('[data-device]').forEach(b=>b.onclick=()=>{$$('[data-device]').forEach(x=>x.classList.toggle('active',x===b));$('#previewShell').className='preview-shell '+b.dataset.device});
  preview.addEventListener('load',()=>setTimeout(bindPreview,300));
  function injectEditorCss(d){let s=d.getElementById('__easyEditorOverlay');if(!s){s=d.createElement('style');s.id='__easyEditorOverlay';s.textContent='[data-edit-id]:hover{outline:2px solid #f54b96!important;outline-offset:2px!important;cursor:pointer!important}.__easySelected{outline:3px solid #2ba5ff!important;outline-offset:3px!important}[data-editor-hidden="true"]{display:none!important}';d.head.appendChild(s)}}
  function applyPatch(el,p){if(!el||!p)return;if(typeof p.html==='string')el.innerHTML=p.html;if(typeof p.text==='string')el.textContent=p.text;if(typeof p.className==='string')el.className=p.className;if(typeof p.styleText==='string')el.setAttribute('style',p.styleText);if(p.attrs)Object.entries(p.attrs).forEach(([k,v])=>{if(v===null||v===undefined||v==='')el.removeAttribute(k);else el.setAttribute(k,String(v))});if(p.hidden===true)el.dataset.editorHidden='true';else if(p.hidden===false)delete el.dataset.editorHidden}
  function applyTheme(){const d=doc();if(!d)return;const t=state.site?.theme||{},m={primary:'--primary',background:'--background',foreground:'--foreground',card:'--card',muted:'--muted-foreground'};Object.entries(m).forEach(([k,v])=>{if(t[k])d.documentElement.style.setProperty(v,t[k]);else d.documentElement.style.removeProperty(v)});let s=d.getElementById('site-custom-css');if(!s){s=d.createElement('style');s.id='site-custom-css';d.head.appendChild(s)}s.textContent=state.site?.customCss||'';if(state.site?.title)d.title=state.site.title}
  function youtubeId(u){try{const x=new URL(u);if(x.hostname.includes('youtu.be'))return x.pathname.split('/').filter(Boolean)[0]||'';if(x.hostname.includes('youtube.com')){if(x.pathname.startsWith('/embed/')||x.pathname.startsWith('/shorts/'))return x.pathname.split('/')[2]||'';return x.searchParams.get('v')||''}}catch{}return''}
  function vimeoId(u){try{const x=new URL(u);if(!x.hostname.includes('vimeo.com'))return'';return x.pathname.split('/').filter(Boolean).find(v=>/^\d+$/.test(v))||''}catch{}return''}
  function makePlayer(d,url,c={}){const y=youtubeId(url),v=vimeoId(url),a=c.autoplay?'1':'0',ctrl=c.controls===false?'0':'1';if(y){const f=d.createElement('iframe');f.src=`https://www.youtube.com/embed/${encodeURIComponent(y)}?autoplay=${a}&controls=${ctrl}&rel=0&playsinline=1`;f.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';f.allowFullscreen=true;return f}if(v){const f=d.createElement('iframe');f.src=`https://player.vimeo.com/video/${encodeURIComponent(v)}?autoplay=${a}&controls=${ctrl}`;f.allow='autoplay; fullscreen; picture-in-picture';f.allowFullscreen=true;return f}if(/\.(mp4|webm|ogg)(?:$|[?#])/i.test(url)||url.startsWith('/media/')){const z=d.createElement('video');z.src=url;z.playsInline=true;z.preload='metadata';z.controls=c.controls!==false;if(c.autoplay){z.autoplay=true;z.muted=true}return z}const f=d.createElement('iframe');f.src=url;f.allow='autoplay; fullscreen; picture-in-picture';f.allowFullscreen=true;return f}
  function mountVideo(id,c={}){const d=doc(),src=d?.querySelector(`[data-edit-id="${CSS.escape(id)}"]`);if(!src)return;const host=src.parentElement;if(!host)return;host.querySelectorAll(`:scope > .site-video-player[data-video-for="${CSS.escape(id)}"]`).forEach(x=>x.remove());src.hidden=false;src.removeAttribute('aria-hidden');const url=String(c.url||'').trim();if(!url)return;src.hidden=true;src.setAttribute('aria-hidden','true');const w=d.createElement('div');w.className='site-video-player';w.dataset.videoFor=id;w.style.cssText='position:absolute;inset:0;width:100%;height:100%;overflow:hidden;background:#000;';const open=()=>{w.innerHTML='';const p=makePlayer(d,url,c);p.style.cssText='width:100%;height:100%;border:0;display:block;object-fit:cover;';w.appendChild(p)};if(c.poster&&!c.autoplay){const b=d.createElement('button');b.type='button';b.style.cssText=`position:absolute;inset:0;width:100%;height:100%;border:0;padding:0;cursor:pointer;background:#000 url("${String(c.poster).replace(/"/g,'%22')}") center/cover no-repeat;`;b.innerHTML='<span style="position:absolute;inset:0;background:rgba(0,0,0,.18)"></span><span style="position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:58px;height:58px;border-radius:999px;background:#dc2626;color:white;display:grid;place-items:center">▶</span>';b.onclick=open;w.appendChild(b)}else open();host.appendChild(w)}
  function applyVideos(){const d=doc();if(!d)return;d.querySelectorAll('.site-video-player').forEach(x=>x.remove());Object.entries(state.videos||{}).forEach(([id,c])=>mountVideo(id,c||{}))}
  function applyState(){const d=doc();if(!d)return;Object.entries(state.patches||{}).forEach(([id,p])=>applyPatch(d.querySelector(`[data-edit-id="${CSS.escape(id)}"]`),p));const main=d.querySelector('main');if(main&&state.sectionOrder?.length){const m=new Map([...main.querySelectorAll(':scope > section[data-edit-id]')].map(s=>[s.dataset.editId,s]));state.sectionOrder.forEach(id=>m.get(id)&&main.appendChild(m.get(id)))}applyTheme();applyVideos()}
  function bindPreview(){const d=doc();if(!d)return;injectEditorCss(d);applyState();d.addEventListener('click',e=>{let el=e.target.closest?.('[data-edit-id]');const v=e.target.closest?.('.site-video-player');if(v?.dataset.videoFor)el=d.querySelector(`[data-edit-id="${CSS.escape(v.dataset.videoFor)}"]`);if(!el)return;e.preventDefault();e.stopPropagation();selectElement(el.dataset.editId)},true);d.addEventListener('submit',e=>{e.preventDefault();e.stopPropagation()},true);renderEverything();setDirty(dirty)}
  function selectElement(id){const d=doc();if(!d)return;d.querySelectorAll('.__easySelected').forEach(x=>x.classList.remove('__easySelected'));const el=d.querySelector(`[data-edit-id="${CSS.escape(id)}"]`);if(!el)return;el.classList.add('__easySelected');selectedId=id;renderSelected(el);openView('selected')}
  function sectionName(s,i){const t=(s.querySelector('h1,h2,h3')?.textContent||'').trim().replace(/\s+/g,' ');if(i===0)return'Capa / abertura';if(/alunas|conquistando/i.test(t))return'Resultados das alunas';if(/aprender|speed lash/i.test(t))return'Conteúdo do curso';if(/bônus|bonus/i.test(t))return'Bônus';if(/perguntas frequentes/i.test(t))return'Perguntas frequentes';return t.slice(0,55)||`Seção ${i+1}`}
  function isVideoBlock(el){if(!el)return false;if(el.matches('video,iframe'))return true;if(el.tagName!=='BUTTON')return false;const a=(el.getAttribute('aria-label')||'').toLowerCase();return!!el.querySelector('img')&&(/assistir|vídeo|video|conteúdo|conteudo|conheça|conheca/.test(a)||!!el.querySelector('svg'))}
  function isTextCandidate(el){if(!el||isVideoBlock(el)||!/^(H1|H2|H3|H4|P|A|BUTTON|LI|SPAN|STRONG|SMALL)$/.test(el.tagName)||!(el.textContent||'').trim())return false;if(['SPAN','STRONG','SMALL'].includes(el.tagName)){const p=el.parentElement?.closest('h1[data-edit-id],h2[data-edit-id],h3[data-edit-id],h4[data-edit-id],p[data-edit-id],a[data-edit-id],button[data-edit-id]');if(p&&p!==el)return false}return true}
  function leafTextNodes(el){const d=el.ownerDocument,w=d.createTreeWalker(el,NodeFilter.SHOW_TEXT,{acceptNode(n){if(!n.nodeValue?.trim())return NodeFilter.FILTER_REJECT;const p=n.parentElement;if(!p||['SCRIPT','STYLE','SVG','PATH'].includes(p.tagName))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}}),a=[];let n;while((n=w.nextNode()))a.push(n);return a}
  function elementLabel(el){if(el.tagName==='H1')return'Título principal';if(/^H[2-4]$/.test(el.tagName))return'Título da seção';if(el.tagName==='A')return'Botão / link';if(el.tagName==='BUTTON')return el.hasAttribute('aria-expanded')?'Pergunta':'Botão';if(el.tagName==='LI')return'Item da lista';return'Texto'}
  function updateTextPart(id,i,val){const el=doc()?.querySelector(`[data-edit-id="${CSS.escape(id)}"]`);if(!el)return;const n=leafTextNodes(el);if(!n[i])return;n[i].nodeValue=val;const p=state.patches[id]=state.patches[id]||{};if(el.children.length===0){p.text=el.textContent;delete p.html}else{p.html=el.innerHTML;delete p.text}setDirty(true)}
  function updateAttr(id,n,v){const el=doc()?.querySelector(`[data-edit-id="${CSS.escape(id)}"]`);if(!el)return;if(v)el.setAttribute(n,v);else el.removeAttribute(n);const p=state.patches[id]=state.patches[id]||{};p.attrs={...(p.attrs||{}),[n]:v};setDirty(true)}
  function setHidden(id,h){const el=doc()?.querySelector(`[data-edit-id="${CSS.escape(id)}"]`);if(!el)return;const p=state.patches[id]=state.patches[id]||{};p.hidden=h;if(h)el.dataset.editorHidden='true';else delete el.dataset.editorHidden;setDirty(true);renderSections()}
  function restore(id){delete state.patches[id];delete state.videos[id];setDirty(true);preview.src='/?admin-preview=1&t='+Date.now()}
  function textCard(el,{open=false}={}){const id=el.dataset.editId,d=document.createElement('details');d.className='edit-card';d.open=open;const sn=(el.textContent||'').trim().replace(/\s+/g,' ').slice(0,95);d.innerHTML='<summary><div><div class="item-type"></div><div class="snippet"></div></div><span class="chev">⌄</span></summary><div class="edit-body"></div>';d.querySelector('.item-type').textContent=elementLabel(el);d.querySelector('.snippet').textContent=sn;const body=d.querySelector('.edit-body'),nodes=leafTextNodes(el);nodes.forEach((n,i)=>{const w=document.createElement('div');w.className='mini-field';const l=document.createElement('label');l.textContent=nodes.length===1?'Texto':`Parte ${i+1}`;const inp=n.nodeValue.length>110?document.createElement('textarea'):document.createElement('input');inp.value=n.nodeValue.trim();inp.oninput=()=>updateTextPart(id,i,inp.value);w.append(l,inp);body.appendChild(w)});if(el.tagName==='A'){const w=document.createElement('div');w.className='mini-field';w.innerHTML='<label>Para onde este botão leva?</label>';const inp=document.createElement('input');inp.value=el.getAttribute('href')||'';inp.placeholder='https://... ou #secao';inp.oninput=()=>updateAttr(id,'href',inp.value);w.appendChild(inp);body.appendChild(w)}const a=document.createElement('div');a.className='inline-actions';const h=document.createElement('button');h.className='mini-btn';h.type='button';h.textContent=el.dataset.editorHidden==='true'?'Mostrar item':'Ocultar item';h.onclick=()=>setHidden(id,el.dataset.editorHidden!=='true');const r=document.createElement('button');r.className='mini-btn danger';r.type='button';r.textContent='Restaurar original';r.onclick=()=>restore(id);a.append(h,r);body.appendChild(a);return d}
  async function upload(file){if(!file)throw new Error('Selecione um arquivo.');const f=new FormData();f.append('file',file);return api('/api/upload',{method:'POST',body:f})}
  function imageCard(img){const id=img.dataset.editId,c=document.createElement('div');c.className='media-card';const src=img.getAttribute('src')||'';c.innerHTML='<div class="media-top"><img class="media-thumb" alt=""><div><div class="media-title">Imagem</div><div class="media-sub"></div><div class="inline-actions"></div></div></div><details class="advanced-box"><summary>Usar imagem por link</summary></details>';c.querySelector('.media-thumb').src=src;c.querySelector('.media-sub').textContent=(img.getAttribute('alt')||'Imagem do site').slice(0,80);const a=c.querySelector('.inline-actions'),lab=document.createElement('label');lab.className='file-label';lab.innerHTML='Trocar imagem<input type="file" accept="image/*">';lab.querySelector('input').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const x=await upload(f);updateAttr(id,'src',x.url);c.querySelector('.media-thumb').src=x.url;toast('Imagem atualizada.')}catch(err){toast(err.message)}};const see=document.createElement('button');see.className='mini-btn';see.type='button';see.textContent='Ver no site';see.onclick=()=>selectElement(id);a.append(lab,see);const inp=document.createElement('input');inp.className='input';inp.value=src;inp.placeholder='https://...';inp.onchange=()=>{updateAttr(id,'src',inp.value);c.querySelector('.media-thumb').src=inp.value};c.querySelector('details').appendChild(inp);return c}
  function videoCard(src){const id=src.dataset.editId,poster0=src.querySelector('img')?.getAttribute('src')||'';if(!state.videos[id])state.videos[id]={url:'',poster:poster0,autoplay:false,controls:true};const cfg=state.videos[id],c=document.createElement('div');c.className='media-card';c.innerHTML='<div class="media-top"><div class="media-thumb video-thumb"><img class="media-thumb" alt=""></div><div><div class="media-title">Vídeo</div><div class="media-sub">Cole YouTube, Vimeo ou MP4. Também pode enviar um vídeo pequeno.</div></div></div><div class="edit-body" style="margin:12px -13px -13px"><div class="mini-field"><label>Link do vídeo</label><input class="video-url" type="text" placeholder="Cole aqui o link do vídeo"></div><div class="inline-actions media-actions"></div><div class="switch-row"><label class="switch"><input class="controls" type="checkbox"> Mostrar controles</label><label class="switch"><input class="autoplay" type="checkbox"> Iniciar automaticamente</label></div><div class="mini-field" style="margin-top:12px"><label>Capa do vídeo</label><div class="inline-actions poster-actions"></div></div></div>';const thumb=c.querySelector('.video-thumb img');thumb.src=cfg.poster||poster0;const u=c.querySelector('.video-url'),ctrl=c.querySelector('.controls'),auto=c.querySelector('.autoplay');u.value=cfg.url||'';ctrl.checked=cfg.controls!==false;auto.checked=!!cfg.autoplay;const commit=()=>{state.videos[id]={...state.videos[id],url:u.value.trim(),controls:ctrl.checked,autoplay:auto.checked,poster:state.videos[id].poster||poster0};setDirty(true);applyVideos()};u.oninput=commit;ctrl.onchange=commit;auto.onchange=commit;const a=c.querySelector('.media-actions'),up=document.createElement('label');up.className='file-label';up.innerHTML='Enviar vídeo<input type="file" accept="video/mp4,video/webm,video/ogg">';up.querySelector('input').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const x=await upload(f);u.value=x.url;commit();toast('Vídeo enviado e aplicado.')}catch(err){toast(err.message)}};const rm=document.createElement('button');rm.className='mini-btn danger';rm.type='button';rm.textContent='Remover vídeo';rm.onclick=()=>{u.value='';commit()};a.append(up,rm);const pa=c.querySelector('.poster-actions'),pl=document.createElement('label');pl.className='file-label';pl.innerHTML='Trocar capa<input type="file" accept="image/*">';pl.querySelector('input').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const x=await upload(f);state.videos[id].poster=x.url;thumb.src=x.url;setDirty(true);applyVideos();toast('Capa atualizada.')}catch(err){toast(err.message)}};const po=document.createElement('button');po.className='mini-btn';po.type='button';po.textContent='Usar capa original';po.onclick=()=>{state.videos[id].poster=poster0;thumb.src=poster0;setDirty(true);applyVideos()};pa.append(pl,po);return c}
  function renderContent(){const d=doc();if(!d)return;const box=$('#contentSections');box.innerHTML='';const term=$('#contentSearch').value.trim().toLowerCase();[...d.querySelectorAll('main > section[data-edit-id]')].forEach((s,i)=>{const all=[...s.querySelectorAll('[data-edit-id]')].filter(isTextCandidate),f=term?all.filter(x=>(x.textContent||'').toLowerCase().includes(term)):all;if(!f.length)return;const g=document.createElement('details');g.className='section-group';g.open=!!term||i===0;g.innerHTML='<summary><span></span><small></small></summary><div class="section-content"></div>';g.querySelector('summary span').textContent=sectionName(s,i);g.querySelector('summary small').textContent=`${f.length} itens`;f.forEach(x=>g.querySelector('.section-content').appendChild(textCard(x)));box.appendChild(g)});if(!box.children.length)box.innerHTML='<div class="simple-card">Nenhum texto encontrado.</div>'}
  function renderMedia(){const d=doc();if(!d)return;const box=$('#mediaList');box.innerHTML='';const v=[...d.querySelectorAll('button[data-edit-id],video[data-edit-id],iframe[data-edit-id]')].filter(isVideoBlock);if(v.length){const h=document.createElement('div');h.className='eyebrow';h.textContent='VÍDEOS';box.appendChild(h);v.forEach(x=>box.appendChild(videoCard(x)))}const imgs=[...d.querySelectorAll('img[data-edit-id]')].filter(i=>!v.some(x=>x.contains(i)));if(imgs.length){const h=document.createElement('div');h.className='eyebrow';h.textContent='IMAGENS';box.appendChild(h);imgs.forEach(x=>box.appendChild(imageCard(x)))}if(!v.length&&!imgs.length)box.innerHTML='<div class="simple-card">Nenhuma mídia editável encontrada.</div>'}
  function renderSections(){const d=doc();if(!d)return;const box=$('#sectionList');box.innerHTML='';const main=d.querySelector('main'),ss=[...main.querySelectorAll(':scope > section[data-edit-id]')];if(!state.sectionOrder?.length)state.sectionOrder=ss.map(s=>s.dataset.editId);ss.forEach((s,i)=>{const id=s.dataset.editId,r=document.createElement('div');r.className='section-row';r.draggable=true;r.dataset.id=id;r.innerHTML='<button class="drag-handle" type="button">⋮⋮</button><div><strong></strong><small></small></div><div class="section-tools"><button class="mini-btn up" type="button">↑</button><button class="mini-btn down" type="button">↓</button><label class="visibility"><input type="checkbox"> Visível</label></div>';r.querySelector('strong').textContent=sectionName(s,i);r.querySelector('small').textContent=`Seção ${i+1}`;const vis=r.querySelector('input');vis.checked=s.dataset.editorHidden!=='true';vis.onchange=()=>setHidden(id,!vis.checked);r.querySelector('.up').onclick=()=>moveSection(id,-1);r.querySelector('.down').onclick=()=>moveSection(id,1);r.ondragstart=()=>r.classList.add('dragging');r.ondragend=()=>r.classList.remove('dragging');r.ondragover=e=>e.preventDefault();r.ondrop=e=>{e.preventDefault();const z=box.querySelector('.dragging');if(!z||z===r)return;const q=r.getBoundingClientRect();box.insertBefore(z,e.clientY<q.top+q.height/2?r:r.nextSibling);applyOrderFromUI()};box.appendChild(r)})}
  function applyOrderFromUI(){const ids=[...$('#sectionList').querySelectorAll('.section-row')].map(r=>r.dataset.id);state.sectionOrder=ids;const main=doc()?.querySelector('main');if(main){const m=new Map([...main.querySelectorAll(':scope > section[data-edit-id]')].map(s=>[s.dataset.editId,s]));ids.forEach(id=>m.get(id)&&main.appendChild(m.get(id)))}setDirty(true);renderSections();renderContent()}
  function moveSection(id,d){const rs=[...$('#sectionList').querySelectorAll('.section-row')],i=rs.findIndex(r=>r.dataset.id===id),j=i+d;if(i<0||j<0||j>=rs.length)return;if(d<0)$('#sectionList').insertBefore(rs[i],rs[j]);else $('#sectionList').insertBefore(rs[j],rs[i]);applyOrderFromUI()}
  function renderSelected(el){const b=$('#selectedEditor');b.innerHTML='';const x=document.createElement('div');x.className='selected-badge';x.textContent='Você está editando: '+(isVideoBlock(el)?'Vídeo':el.tagName==='IMG'?'Imagem':elementLabel(el));b.appendChild(x);if(isVideoBlock(el))b.appendChild(videoCard(el));else if(el.tagName==='IMG')b.appendChild(imageCard(el));else if(isTextCandidate(el))b.appendChild(textCard(el,{open:true}));else{const c=document.createElement('div');c.className='simple-card';const h=document.createElement('button');h.className='btn secondary wide';h.textContent=el.dataset.editorHidden==='true'?'Mostrar bloco':'Ocultar bloco';h.onclick=()=>setHidden(el.dataset.editId,el.dataset.editorHidden!=='true');const r=document.createElement('button');r.className='btn danger wide';r.style.marginTop='8px';r.textContent='Restaurar bloco original';r.onclick=()=>restore(el.dataset.editId);c.append(h,r);b.appendChild(c)}}
  function syncSiteFields(){$('#siteTitle').value=state.site?.title||'';$('#siteDescription').value=state.site?.description||'';$('#customCss').value=state.site?.customCss||'';const t=state.site?.theme||{};Object.entries(DEFAULT_THEME).forEach(([k,v])=>{$('#theme'+k[0].toUpperCase()+k.slice(1)).value=t[k]||v});syncRaw()}
  ['Primary','Background','Foreground','Card','Muted'].forEach(n=>$('#theme'+n).oninput=e=>{state.site.theme=state.site.theme||{};state.site.theme[n.toLowerCase()]=e.target.value;applyTheme();setDirty(true)});$('#resetThemeBtn').onclick=()=>{state.site.theme={};syncSiteFields();applyTheme();setDirty(true);toast('Cores originais restauradas.')};$('#siteTitle').oninput=e=>{state.site.title=e.target.value;applyTheme();setDirty(true)};$('#siteDescription').oninput=e=>{state.site.description=e.target.value;setDirty(true)};$('#customCss').oninput=e=>{state.site.customCss=e.target.value;applyTheme();setDirty(true)};$('#contentSearch').oninput=renderContent;
  function syncRaw(){const r=$('#rawJson');if(r&&document.activeElement!==r)r.value=JSON.stringify(state,null,2)}$('#applyJsonBtn').onclick=()=>{try{ensureState(JSON.parse($('#rawJson').value));syncSiteFields();applyState();renderEverything();setDirty(true);toast('Configuração aplicada.')}catch(e){toast('Configuração inválida: '+e.message)}};$('#resetAllBtn').onclick=()=>{if(!confirm('Tem certeza que quer apagar todas as alterações feitas pelo painel?'))return;ensureState({});syncSiteFields();setDirty(true);preview.src='/?admin-preview=1&t='+Date.now()};
  function renderEverything(){if(!doc())return;renderContent();renderMedia();renderSections();if(selectedId){const e=doc().querySelector(`[data-edit-id="${CSS.escape(selectedId)}"]`);if(e)renderSelected(e)}syncRaw()}
  window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});checkSession();
})();