(() => {
  const DEFAULT_STATE={version:4,patches:{},sectionOrder:[],site:{title:'',description:'',customCss:'',theme:{}},videos:{}};
  const DEFAULT_THEME={primary:'#fa4a98',background:'#0a0508',foreground:'#fff7fb',card:'#171015',muted:'#b7aab1'};
  let state=structuredClone(DEFAULT_STATE),dirty=false;
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],preview=$('#preview');

  function ensureState(data={}){state={...DEFAULT_STATE,...data,patches:{...(data.patches||{})},videos:{...(data.videos||{})},site:{...DEFAULT_STATE.site,...(data.site||{}),theme:{...(data.site?.theme||{})}}}}
  function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.add('hidden'),3200)}
  function setDirty(v=true){dirty=v;const s=$('#saveStatus');s.classList.toggle('dirty',v);s.classList.toggle('saved',!v);s.querySelector('span:last-child').textContent=v?'Alterações não salvas':'Salvo'}
  async function api(url,opts={}){const headers={...(opts.headers||{})};if(opts.body&&!(opts.body instanceof FormData))headers['content-type']='application/json';const r=await fetch(url,{...opts,headers});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`Erro ${r.status}`);return d}
  function doc(){return preview.contentDocument}

  async function checkStorage(){try{const h=await api('/api/health');$('#storageWarning').classList.toggle('hidden',!!h.kv);return !!h.kv}catch{$('#storageWarning').classList.remove('hidden');return false}}
  async function showApp(){$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');await checkStorage();try{ensureState(await api('/api/content'))}catch{ensureState({})}syncSiteFields();preview.src='/?admin-preview=1&t='+Date.now()}
  async function save(){try{$('#saveBtn').disabled=true;state.version=4;await api('/api/content',{method:'PUT',body:JSON.stringify(state)});setDirty(false);toast('Alterações salvas.')}catch(e){toast(e.message)}finally{$('#saveBtn').disabled=false}}

  $('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';try{await api('/api/login',{method:'POST',body:JSON.stringify({password:$('#password').value})});await showApp()}catch(err){$('#loginError').textContent=err.message}});
  $('#logoutBtn').onclick=async()=>{await api('/api/logout',{method:'POST'}).catch(()=>{});location.reload()};
  $('#saveBtn').onclick=save;
  $('#previewBtn').onclick=()=>{$('#previewModal').classList.remove('hidden');document.body.style.overflow='hidden'};
  $('#closePreviewBtn').onclick=()=>{$('#previewModal').classList.add('hidden');document.body.style.overflow=''};
  $('#previewModal').addEventListener('click',e=>{if(e.target===$('#previewModal'))$('#closePreviewBtn').click()});
  $('#reloadBtn').onclick=()=>preview.src='/?admin-preview=1&t='+Date.now();
  $$('[data-device]').forEach(b=>b.onclick=()=>{$$('[data-device]').forEach(x=>x.classList.toggle('active',x===b));$('#previewShell').className='preview-shell '+b.dataset.device});
  $$('.nav-item').forEach(b=>b.onclick=()=>{const view=b.dataset.view;$$('.nav-item').forEach(x=>x.classList.toggle('active',x===b));$$('[data-view-panel]').forEach(x=>x.classList.toggle('active',x.dataset.viewPanel===view));window.scrollTo({top:0,behavior:'smooth'})});

  function applyPatch(el,p){if(!el||!p)return;if(typeof p.html==='string')el.innerHTML=p.html;if(typeof p.text==='string')el.textContent=p.text;if(typeof p.className==='string')el.className=p.className;if(typeof p.styleText==='string')el.setAttribute('style',p.styleText);if(p.attrs)Object.entries(p.attrs).forEach(([k,v])=>{if(v===null||v===undefined||v==='')el.removeAttribute(k);else el.setAttribute(k,String(v))});if(p.hidden===true)el.dataset.editorHidden='true';else if(p.hidden===false)delete el.dataset.editorHidden}
  function applyTheme(){const d=doc();if(!d)return;const t=state.site?.theme||{},m={primary:'--primary',background:'--background',foreground:'--foreground',card:'--card',muted:'--muted-foreground'};Object.entries(m).forEach(([k,v])=>{if(t[k])d.documentElement.style.setProperty(v,t[k]);else d.documentElement.style.removeProperty(v)});let s=d.getElementById('site-custom-css');if(!s){s=d.createElement('style');s.id='site-custom-css';d.head.appendChild(s)}s.textContent=state.site?.customCss||'';if(state.site?.title)d.title=state.site.title}
  function applyOrder(){const d=doc(),main=d?.querySelector('main');if(!main||!state.sectionOrder?.length)return;const map=new Map([...main.querySelectorAll(':scope > section[data-edit-id]')].map(x=>[x.dataset.editId,x]));state.sectionOrder.forEach(id=>map.get(id)&&main.appendChild(map.get(id)))}

  function youtubeId(u){try{const x=new URL(u);if(x.hostname.includes('youtu.be'))return x.pathname.split('/').filter(Boolean)[0]||'';if(x.hostname.includes('youtube.com')){if(x.pathname.startsWith('/embed/')||x.pathname.startsWith('/shorts/'))return x.pathname.split('/')[2]||'';return x.searchParams.get('v')||''}}catch{}return''}
  function vimeoId(u){try{const x=new URL(u);if(!x.hostname.includes('vimeo.com'))return'';return x.pathname.split('/').filter(Boolean).find(v=>/^\d+$/.test(v))||''}catch{}return''}
  function makePlayer(d,url,c={}){const y=youtubeId(url),v=vimeoId(url),auto=c.autoplay?'1':'0',ctrl=c.controls===false?'0':'1';if(y){const f=d.createElement('iframe');f.src=`https://www.youtube.com/embed/${encodeURIComponent(y)}?autoplay=${auto}&controls=${ctrl}&rel=0&playsinline=1`;f.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';f.allowFullscreen=true;return f}if(v){const f=d.createElement('iframe');f.src=`https://player.vimeo.com/video/${encodeURIComponent(v)}?autoplay=${auto}&controls=${ctrl}`;f.allow='autoplay; fullscreen; picture-in-picture';f.allowFullscreen=true;return f}const z=d.createElement('video');z.src=url;z.playsInline=true;z.preload='metadata';z.controls=c.controls!==false;if(c.autoplay){z.autoplay=true;z.muted=true}return z}
  function mountVideo(id,c={}){const d=doc(),src=d?.querySelector(`[data-edit-id="${CSS.escape(id)}"]`);if(!src)return;const host=src.parentElement;if(!host)return;host.querySelectorAll(`:scope > .site-video-player[data-video-for="${CSS.escape(id)}"]`).forEach(x=>x.remove());src.hidden=false;const url=String(c.url||'').trim();if(!url)return;src.hidden=true;const w=d.createElement('div');w.className='site-video-player';w.dataset.videoFor=id;w.style.cssText='position:absolute;inset:0;width:100%;height:100%;overflow:hidden;background:#000;';const open=()=>{w.innerHTML='';const p=makePlayer(d,url,c);p.style.cssText='width:100%;height:100%;border:0;display:block;object-fit:cover;';w.appendChild(p)};if(c.poster&&!c.autoplay){const b=d.createElement('button');b.type='button';b.style.cssText=`position:absolute;inset:0;width:100%;height:100%;border:0;padding:0;cursor:pointer;background:#000 url("${String(c.poster).replace(/"/g,'%22')}") center/cover no-repeat;`;b.innerHTML='<span style="position:absolute;inset:0;background:rgba(0,0,0,.15)"></span><span style="position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:58px;height:58px;border-radius:999px;background:#dc2626;color:white;display:grid;place-items:center">▶</span>';b.onclick=open;w.appendChild(b)}else open();host.appendChild(w)}
  function applyVideos(){const d=doc();if(!d)return;d.querySelectorAll('.site-video-player').forEach(x=>x.remove());Object.entries(state.videos||{}).forEach(([id,c])=>mountVideo(id,c||{}))}
  function applyState(){const d=doc();if(!d)return;Object.entries(state.patches||{}).forEach(([id,p])=>applyPatch(d.querySelector(`[data-edit-id="${CSS.escape(id)}"]`),p));applyOrder();applyTheme();applyVideos()}

  function sectionName(s,i){const t=(s.querySelector('h1,h2,h3')?.textContent||'').trim().replace(/\s+/g,' ');if(i===0)return'Capa / abertura';if(/alunas|conquistando/i.test(t))return'Resultados das alunas';if(/aprender/i.test(t))return'Conteúdo do curso';if(/certificados/i.test(t))return'Certificados';if(/lyzandra/i.test(t))return'Sobre Lyzandra';if(/perguntas frequentes/i.test(t))return'Perguntas frequentes';return t.slice(0,65)||`Seção ${i+1}`}
  function isVideoBlock(el){if(!el)return false;if(el.matches('video,iframe'))return true;if(el.tagName!=='BUTTON')return false;const a=(el.getAttribute('aria-label')||'').toLowerCase();return!!el.querySelector('img')&&(/assistir|vídeo|video|conteúdo|conteudo|conheça|conheca/.test(a)||!!el.querySelector('svg'))}
  function isTextCandidate(el){if(!el||isVideoBlock(el)||!/^(H1|H2|H3|H4|P|A|BUTTON|LI|SPAN|STRONG|SMALL)$/.test(el.tagName)||!(el.textContent||'').trim())return false;if(['SPAN','STRONG','SMALL'].includes(el.tagName)){const p=el.parentElement?.closest('h1[data-edit-id],h2[data-edit-id],h3[data-edit-id],h4[data-edit-id],p[data-edit-id],a[data-edit-id],button[data-edit-id]');if(p&&p!==el)return false}return true}
  function leafTextNodes(el){const d=el.ownerDocument,w=d.createTreeWalker(el,NodeFilter.SHOW_TEXT,{acceptNode(n){if(!n.nodeValue?.trim())return NodeFilter.FILTER_REJECT;const p=n.parentElement;if(!p||['SCRIPT','STYLE','SVG','PATH'].includes(p.tagName))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}}),arr=[];let n;while((n=w.nextNode()))arr.push(n);return arr}
  function elementLabel(el){if(el.tagName==='H1')return'Título principal';if(/^H[2-4]$/.test(el.tagName))return'Título';if(el.tagName==='A')return'Botão';if(el.tagName==='BUTTON')return el.hasAttribute('aria-expanded')?'Pergunta':'Botão';if(el.tagName==='LI')return'Item da lista';return'Texto'}
  function updateTextPart(id,index,value){const el=doc()?.querySelector(`[data-edit-id="${CSS.escape(id)}"]`);if(!el)return;const nodes=leafTextNodes(el);if(!nodes[index])return;nodes[index].nodeValue=value;const p=state.patches[id]=state.patches[id]||{};if(el.children.length===0){p.text=el.textContent;delete p.html}else{p.html=el.innerHTML;delete p.text}setDirty(true)}
  function updateAttr(id,name,value){const el=doc()?.querySelector(`[data-edit-id="${CSS.escape(id)}"]`);if(!el)return;if(value)el.setAttribute(name,value);else el.removeAttribute(name);const p=state.patches[id]=state.patches[id]||{};p.attrs={...(p.attrs||{}),[name]:value};setDirty(true)}
  function setHidden(id,hidden){const el=doc()?.querySelector(`[data-edit-id="${CSS.escape(id)}"]`);if(!el)return;const p=state.patches[id]=state.patches[id]||{};p.hidden=hidden;if(hidden)el.dataset.editorHidden='true';else delete el.dataset.editorHidden;setDirty(true);renderSections()}

  function makeTextCard(el){const id=el.dataset.editId,c=document.createElement('div');c.className='text-card';const title=document.createElement('div');title.className='text-card-title';title.textContent=elementLabel(el);c.appendChild(title);const nodes=leafTextNodes(el);nodes.forEach((n,i)=>{const wrap=document.createElement('div');wrap.className='mini-field';const label=document.createElement('label');label.textContent=nodes.length===1?'Texto':`Parte ${i+1}`;const inp=n.nodeValue.trim().length>110?document.createElement('textarea'):document.createElement('input');inp.value=n.nodeValue.trim();inp.oninput=()=>updateTextPart(id,i,inp.value);wrap.append(label,inp);c.appendChild(wrap)});if(el.tagName==='A'){const wrap=document.createElement('div');wrap.className='mini-field';const label=document.createElement('label');label.textContent='Para onde o botão leva?';const inp=document.createElement('input');inp.value=el.getAttribute('href')||'';inp.placeholder='Cole um link ou use #secao';inp.oninput=()=>updateAttr(id,'href',inp.value);wrap.append(label,inp);c.appendChild(wrap)}return c}
  function renderContent(){const d=doc();if(!d)return;const box=$('#contentSections');box.innerHTML='';const term=$('#contentSearch').value.trim().toLowerCase();[...d.querySelectorAll('main > section[data-edit-id]')].forEach((s,i)=>{const all=[...s.querySelectorAll('[data-edit-id]')].filter(isTextCandidate),items=term?all.filter(x=>(x.textContent||'').toLowerCase().includes(term)):all;if(!items.length)return;const g=document.createElement('details');g.className='section-group';g.open=!!term||i===0;const sum=document.createElement('summary'),name=document.createElement('span'),count=document.createElement('small');name.textContent=sectionName(s,i);count.textContent=`${items.length} itens`;sum.append(name,count);const body=document.createElement('div');body.className='section-body';items.forEach(x=>body.appendChild(makeTextCard(x)));g.append(sum,body);box.appendChild(g)});if(!box.children.length)box.innerHTML='<div class="card">Nenhum texto encontrado.</div>'}

  async function upload(file){if(!file)throw new Error('Selecione um arquivo.');const fd=new FormData();fd.append('file',file);return api('/api/upload',{method:'POST',body:fd})}
  function imageCard(img){const id=img.dataset.editId,c=document.createElement('div');c.className='media-card';const src=img.getAttribute('src')||'';c.innerHTML='<div class="media-head"><img class="media-thumb" alt=""><div><div class="media-title">Foto / imagem</div><div class="media-sub">Troque por um arquivo do computador.</div><div class="inline-actions"></div></div></div><div class="media-body"><div class="mini-field"><label>Ou cole o link de uma imagem</label><input class="link-input" type="text"></div></div>';c.querySelector('.media-thumb').src=src;const actions=c.querySelector('.inline-actions'),lab=document.createElement('label');lab.className='file-label';lab.innerHTML='Trocar imagem<input type="file" accept="image/*">';lab.querySelector('input').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const x=await upload(f);updateAttr(id,'src',x.url);c.querySelector('.media-thumb').src=x.url;toast('Imagem atualizada.')}catch(err){toast(err.message)}};actions.appendChild(lab);const link=c.querySelector('.link-input');link.value=src;link.onchange=()=>{updateAttr(id,'src',link.value);c.querySelector('.media-thumb').src=link.value};return c}
  function videoCard(src,index){const id=src.dataset.editId,poster0=src.querySelector('img')?.getAttribute('src')||'';if(!state.videos[id])state.videos[id]={url:'',poster:poster0,autoplay:false,controls:true};const cfg=state.videos[id],c=document.createElement('div');c.className='media-card';c.innerHTML='<div class="media-head"><div class="media-thumb-wrap video"><img class="media-thumb" alt=""></div><div><div class="media-title"></div><div class="media-sub">Envie um vídeo ou cole YouTube, Vimeo ou MP4.</div></div></div><div class="media-body"><div class="upload-main"></div><div class="mini-field"><label>Link do vídeo</label><input class="video-url" type="text" placeholder="https://youtube.com/... ou link MP4"></div><div class="switch-row"><label class="switch"><input class="controls" type="checkbox"> Mostrar controles</label><label class="switch"><input class="autoplay" type="checkbox"> Iniciar automaticamente</label></div><div class="mini-field"><label>Capa do vídeo</label><div class="inline-actions poster-actions"></div></div></div>';c.querySelector('.media-title').textContent=`Vídeo ${index+1}`;const thumb=c.querySelector('.media-thumb');thumb.src=cfg.poster||poster0;const url=c.querySelector('.video-url'),controls=c.querySelector('.controls'),autoplay=c.querySelector('.autoplay');url.value=cfg.url||'';controls.checked=cfg.controls!==false;autoplay.checked=!!cfg.autoplay;const commit=()=>{state.videos[id]={...state.videos[id],url:url.value.trim(),poster:state.videos[id].poster||poster0,controls:controls.checked,autoplay:autoplay.checked};setDirty(true);applyVideos()};url.onchange=commit;controls.onchange=commit;autoplay.onchange=commit;const actions=c.querySelector('.upload-main'),up=document.createElement('label');up.className='file-label';up.innerHTML='Enviar vídeo do computador<input type="file" accept="video/*">';up.querySelector('input').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const x=await upload(f);url.value=x.url;commit();toast('Vídeo enviado e aplicado.')}catch(err){toast(err.message)}};const remove=document.createElement('button');remove.className='mini-btn danger';remove.type='button';remove.textContent='Remover vídeo';remove.onclick=()=>{url.value='';commit()};actions.append(up,remove);const pa=c.querySelector('.poster-actions'),pl=document.createElement('label');pl.className='file-label';pl.innerHTML='Trocar capa<input type="file" accept="image/*">';pl.querySelector('input').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const x=await upload(f);state.videos[id].poster=x.url;thumb.src=x.url;setDirty(true);applyVideos();toast('Capa atualizada.')}catch(err){toast(err.message)}};const original=document.createElement('button');original.className='mini-btn';original.type='button';original.textContent='Usar capa original';original.onclick=()=>{state.videos[id].poster=poster0;thumb.src=poster0;setDirty(true);applyVideos()};pa.append(pl,original);return c}
  function renderMedia(){const d=doc();if(!d)return;const box=$('#mediaList');box.innerHTML='';const videos=[...d.querySelectorAll('button[data-edit-id],video[data-edit-id],iframe[data-edit-id]')].filter(isVideoBlock);if(videos.length){videos.forEach((x,i)=>box.appendChild(videoCard(x,i)))}const imgs=[...d.querySelectorAll('img[data-edit-id]')].filter(img=>!videos.some(v=>v.contains(img)));imgs.forEach(x=>box.appendChild(imageCard(x)));if(!box.children.length)box.innerHTML='<div class="card">Nenhuma foto ou vídeo editável foi encontrado.</div>'}

  function moveSection(id,delta){const d=doc(),main=d?.querySelector('main');if(!main)return;const arr=[...main.querySelectorAll(':scope > section[data-edit-id]')],i=arr.findIndex(s=>s.dataset.editId===id),j=i+delta;if(i<0||j<0||j>=arr.length)return;if(delta<0)main.insertBefore(arr[i],arr[j]);else main.insertBefore(arr[j],arr[i]);state.sectionOrder=[...main.querySelectorAll(':scope > section[data-edit-id]')].map(s=>s.dataset.editId);setDirty(true);renderSections();renderContent()}
  function renderSections(){const d=doc();if(!d)return;const box=$('#sectionList');box.innerHTML='';const ss=[...d.querySelectorAll('main > section[data-edit-id]')];if(!state.sectionOrder?.length)state.sectionOrder=ss.map(s=>s.dataset.editId);ss.forEach((s,i)=>{const id=s.dataset.editId,row=document.createElement('div');row.className='section-row';const info=document.createElement('div'),title=document.createElement('strong'),sub=document.createElement('small');title.textContent=sectionName(s,i);sub.textContent=`Parte ${i+1} do site`;info.append(title,sub);const actions=document.createElement('div');actions.className='section-actions';const up=document.createElement('button');up.className='mini-btn';up.textContent='Subir';up.disabled=i===0;up.onclick=()=>moveSection(id,-1);const down=document.createElement('button');down.className='mini-btn';down.textContent='Descer';down.disabled=i===ss.length-1;down.onclick=()=>moveSection(id,1);const vis=document.createElement('label');vis.className='visibility';const ck=document.createElement('input');ck.type='checkbox';ck.checked=s.dataset.editorHidden!=='true';ck.onchange=()=>setHidden(id,!ck.checked);vis.append(ck,document.createTextNode(' Mostrar'));actions.append(up,down,vis);row.append(info,actions);box.appendChild(row)})}

  function syncSiteFields(){const t=state.site?.theme||{};$('#siteTitle').value=state.site?.title||'';$('#siteDescription').value=state.site?.description||'';Object.entries(DEFAULT_THEME).forEach(([k,v])=>{$('#theme'+k[0].toUpperCase()+k.slice(1)).value=t[k]||v})}
  ['Primary','Background','Foreground','Card','Muted'].forEach(n=>$('#theme'+n).oninput=e=>{state.site.theme=state.site.theme||{};state.site.theme[n.toLowerCase()]=e.target.value;applyTheme();setDirty(true)});
  $('#resetThemeBtn').onclick=()=>{state.site.theme={};syncSiteFields();applyTheme();setDirty(true);toast('Cores originais restauradas.')};
  $('#siteTitle').oninput=e=>{state.site.title=e.target.value;applyTheme();setDirty(true)};
  $('#siteDescription').oninput=e=>{state.site.description=e.target.value;setDirty(true)};
  $('#contentSearch').oninput=renderContent;

  function renderAll(){applyState();renderContent();renderMedia();renderSections();syncSiteFields()}
  preview.addEventListener('load',()=>setTimeout(()=>{renderAll();setDirty(dirty)},250));
  window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
  (async()=>{try{const s=await api('/api/session');if(s.authenticated)await showApp()}catch{}})();
})();